name: Go

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    tags: 
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Current date
      id: date
      run: echo "date=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV
        
    - name: Set up Go 1.15
      run: echo ${{ env.date }}
        
        
        
        
    
        
        
        
        
        
